version: '3.9'

networks:
  ft_transcendence:
    driver: bridge

services:
  frontend:
    build: requirements/frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ft_transcendence
    hostname: frontend
  
  backend:
    build: requirements/backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - ft_transcendence
    depends_on:
      - database
    hostname: backend
    command: bash -c "npx prisma migrate deploy ;
             npm run start"

  database:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=nest
    networks:
      - ft_transcendence